name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy resume
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to skoji
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PORT: ${{ secrets.DEPLOY_PORT }}
        TZ: 'Asia/Tokyo'
      run: |
        eval `ssh-agent -s`
        echo "${DEPLOY_KEY}" > keyfile && chmod 600 keyfile
        ssh-add keyfile
        rsync -e "ssh -o StrictHostKeyChecking=no -p ${PORT}" -vz resume.html nginx-user@skoji.jp:/usr/share/nginx/html/resume.html
        
        
      
